/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'join'
const service = 'e-learning'
const gateway = 'default'

export const JoinController = {
    // 加入三人行团购
    joinGroupOrder: {
        gateway,
        service,
        controller,
        path: '/api/join/group/{groupId}',
        action: 'joinGroupOrder',
        type: RequestMethod.Post
    }
}
