/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'payed'
const service = 'e-learning'
const gateway = 'default'

export const PayedController = {
    // 外部订单支付成功
    paySuccessRequest: {
        gateway,
        service,
        controller,
        path: '/api/payed/{outTradeNo}',
        action: 'paySuccessRequest',
        type: RequestMethod.Post
    }
}
