/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'question'
const service = 'e-learning'
const gateway = 'default'

export const QuestionController = {
    // 取消点赞
    unstar: {
        gateway,
        service,
        controller,
        path: '/api/question/unstar/{id}',
        action: 'unstar',
        type: RequestMethod.Put
    },
    // 问题点赞
    star: {
        gateway,
        service,
        controller,
        path: '/api/question/star/{id}',
        action: 'star',
        type: RequestMethod.Put
    },
    // 标记问题已完成
    done: {
        gateway,
        service,
        controller,
        path: '/api/question/done/{id}',
        action: 'done',
        type: RequestMethod.Put
    }
}
