/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'syslog'
const service = 'e-learning'
const gateway = 'default'

export const SyslogController = {
    // 操作日志（分页查询)
    pageableSysLog: {
        gateway,
        service,
        controller,
        path: '/syslog/',
        action: 'pageableSysLog',
        type: RequestMethod.Get
    }
}
