/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'training'
const service = 'e-learning'
const gateway = 'default'

export const TrainingController = {
    // 活动详情
    getTrainingDetail: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}',
        action: 'getTrainingDetail',
        type: RequestMethod.Get
    },
    // 更新基本信息
    updateTrainingDetail: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}',
        action: 'updateTrainingDetail',
        type: RequestMethod.Put
    },
    // 更新活动状态
    changeStatus: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/status',
        action: 'changeStatus',
        type: RequestMethod.Put
    },
    // 获取营销配置
    getTrainingSaleConfig: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/sale',
        action: 'getTrainingSaleConfig',
        type: RequestMethod.Get
    },
    // 更新营销配置
    updateTrainingSaleConfig: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/sale',
        action: 'updateTrainingSaleConfig',
        type: RequestMethod.Put
    },
    // 培训发布配置
    getTrainingRelease: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/release',
        action: 'getTrainingRelease',
        type: RequestMethod.Get
    },
    // 获取培训发布配置
    updateTrainingRelease: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/release',
        action: 'updateTrainingRelease',
        type: RequestMethod.Put
    },
    // 活动列表(全部)
    getTrainings: {
        gateway,
        service,
        controller,
        path: '/api/training',
        action: 'getTrainings',
        type: RequestMethod.Get
    },
    // 创建活动
    createTraining: {
        gateway,
        service,
        controller,
        path: '/api/training',
        action: 'createTraining',
        type: RequestMethod.Post
    },
    // （分页）获取学员例表
    getTrainingStudents: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/student',
        action: 'getTrainingStudents',
        type: RequestMethod.Get
    },
    // 增加临时学员
    addStudent: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/student',
        action: 'addStudent',
        type: RequestMethod.Post
    },
    // 获取全部的问题
    getAllQuestions: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/question',
        action: 'getAllQuestions',
        type: RequestMethod.Get
    },
    // 给培训增加提问
    postQuestion: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/question',
        action: 'postQuestion',
        type: RequestMethod.Post
    },
    // 分组查看（学员）
    getTrainingGroupStudents: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/group',
        action: 'getTrainingGroupStudents',
        type: RequestMethod.Get
    },
    // 启动分组
    group: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/group',
        action: 'group',
        type: RequestMethod.Post
    },
    // 把学员加入某个组
    addStudentToGroup: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/group/{gid}',
        action: 'addStudentToGroup',
        type: RequestMethod.Post
    },
    // 搜索学员，包括分组与未分组的
    searchStudent: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/student/search',
        action: 'searchStudent',
        type: RequestMethod.Get
    },
    // （分页）获取全部单订单(admin)
    getTrainingOrders: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/orders',
        action: 'getTrainingOrders',
        type: RequestMethod.Get
    },
    // 获取订单详情
    getTrainingOrderDetail: {
        gateway,
        service,
        controller,
        path: '/api/training/order/{id}',
        action: 'getTrainingOrderDetail',
        type: RequestMethod.Get
    },
    // 从培训中移出学员
    removeStudent: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/student/{sid}',
        action: 'removeStudent',
        type: RequestMethod.Delete
    },
    // 从培训的分组中删除某个学员
    removeStudentGroup: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/group/{sid}',
        action: 'removeStudentGroup',
        type: RequestMethod.Delete
    },
    // 清除分组
    clearGroup: {
        gateway,
        service,
        controller,
        path: '/api/training/{id}/cleargroup',
        action: 'clearGroup',
        type: RequestMethod.Delete
    }
}
