/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { ApiController } from '@/http/controller/user-service/api.controller'

export class ApiService {
  /**
   * 登出
   */
  @Request({
    server: ApiController.logOutCurrentUser,
  })
  public logOutCurrentUser(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 当前用户（分页查询）
   */
  @Request({
    server: ApiController.queryUserLists,
  })
  public queryUserLists(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 
   */
  @Request({
    server: ApiController.getMe,
  })
  public getMe(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 
   */
  @Request({
    server: ApiController.getFoo,
  })
  public getFoo(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 
   */
  @Request({
    server: ApiController.getUserFoo,
  })
  public getUserFoo(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 当用用户
   */
  @Request({
    server: ApiController.currentUser,
  })
  public currentUser(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
