/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { CurrentUserController } from '@/http/controller/user-service/current-user.controller'
import { UserView } from '@/http/model/user-service.model'

export class CurrentUserService {
  /**
   * 当用用户
   */
  @Request({
    server: CurrentUserController.currentUser,
    model: UserView
  })
  public currentUser(
    params?: RequestParams | { [key: string]: any }
  ): Observable<UserView> {
    return RequestParams.create(params).request();
  }
}
