/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { FooController } from '@/http/controller/user-service/foo.controller'

export class FooService {
  /**
   * 
   */
  @Request({
    server: FooController.getFoo,
  })
  public getFoo(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
