/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { Foo2Controller } from '@/http/controller/user-service/foo2.controller'

export class Foo2Service {
  /**
   * 
   */
  @Request({
    server: Foo2Controller.getUserFoo,
  })
  public getUserFoo(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
