/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { LogoutController } from '@/http/controller/user-service/logout.controller'

export class LogoutService {
  /**
   * 登出
   */
  @Request({
    server: LogoutController.logOutCurrentUser,
  })
  public logOutCurrentUser(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
