<<<<<<< HEAD
/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { MicroappController } from '@/http/controller/user-service/microapp.controller'
import { UserView } from '@/http/model/user-service.model'

export class MicroappService {
  /**
   * 同步用户信息
   */
  @Request({
    server: MicroappController.maUserInfoSync,
    model: UserView
  })
  public maUserInfoSync(
    params?: RequestParams | { [key: string]: any }
  ): Observable<UserView> {
    return RequestParams.create(params).request();
  }
  /**
   * 同步用户电话号码
   */
  @Request({
    server: MicroappController.maUserPhoneSync,
    model: UserView
  })
  public maUserPhoneSync(
    params?: RequestParams | { [key: string]: any }
  ): Observable<UserView> {
    return RequestParams.create(params).request();
  }
}
=======
/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { MicroappController } from '@/http/controller/user-service/microapp.controller'

export class MicroappService {
  /**
   * 同步用户信息
   */
  @Request({
    server: MicroappController.maUserInfoSync,
  })
  public maUserInfoSync(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 同步用户电话号码
   */
  @Request({
    server: MicroappController.maUserPhoneSync,
  })
  public maUserPhoneSync(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
>>>>>>> 18d615df41baaca2cddea9b28ebcdc87ad443ba6
