/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { MpuserController } from '@/http/controller/user-service/mpuser.controller'

export class MpuserService {
  /**
   * 微信用户注册
   */
  @Request({
    server: MpuserController.mpUserRegister,
  })
  public mpUserRegister(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
