/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { PublicController } from '@/http/controller/user-service/public.controller'
import { UserView } from '@/http/model/user-service.model'

export class PublicService {
  /**
   * 用户注册
   */
  @Request({
    server: PublicController.createUser,
    model: UserView
  })
  public createUser(
    params?: RequestParams | { [key: string]: any }
  ): Observable<UserView> {
    return RequestParams.create(params).request();
  }
}
