/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { UsersController } from '@/http/controller/user-service/users.controller'

export class UsersService {
  /**
   * 当前用户（分页查询）
   */
  @Request({
    server: UsersController.queryUserLists,
  })
  public queryUserLists(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
