/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'api'
const service = 'uaa'
const gateway = 'default'

export const ApiController = {
    // 登出
    logOutCurrentUser: {
        gateway,
        service,
        controller,
        path: '/api/logout',
        action: 'logOutCurrentUser',
        type: RequestMethod.Post
    },
    // 当前用户（分页查询）
    queryUserLists: {
        gateway,
        service,
        controller,
        path: '/api/users',
        action: 'queryUserLists',
        type: RequestMethod.Get
    },
    // 
    getMe: {
        gateway,
        service,
        controller,
        path: '/api/me',
        action: 'getMe',
        type: RequestMethod.Get
    },
    // 
    getFoo: {
        gateway,
        service,
        controller,
        path: '/api/foo',
        action: 'getFoo',
        type: RequestMethod.Get
    },
    // 
    getUserFoo: {
        gateway,
        service,
        controller,
        path: '/api/foo2',
        action: 'getUserFoo',
        type: RequestMethod.Get
    },
    // 当用用户
    currentUser: {
        gateway,
        service,
        controller,
        path: '/api/currentUser',
        action: 'currentUser',
        type: RequestMethod.Get
    }
}
