/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'foo'
const service = 'uaa'
const gateway = 'default'

export const FooController = {
    // 
    getFoo: {
        gateway,
        service,
        controller,
        path: '/api/foo',
        action: 'getFoo',
        type: RequestMethod.Get
    }
}
