/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'foo2'
const service = 'uaa'
const gateway = 'default'

export const Foo2Controller = {
    // 
    getUserFoo: {
        gateway,
        service,
        controller,
        path: '/api/foo2',
        action: 'getUserFoo',
        type: RequestMethod.Get
    }
}
