/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'logout'
const service = 'uaa'
const gateway = 'default'

export const LogoutController = {
    // 登出
    logOutCurrentUser: {
        gateway,
        service,
        controller,
        path: '/api/logout',
        action: 'logOutCurrentUser',
        type: RequestMethod.Post
    }
}
