/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'mpuser'
const service = 'uaa'
const gateway = 'default'

export const MpuserController = {
    // 微信用户注册
    mpUserRegister: {
        gateway,
        service,
        controller,
        path: '/api/mpuser/register',
        action: 'mpUserRegister',
        type: RequestMethod.Post
    }
}
