/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'public'
const service = 'uaa'
const gateway = 'default'

export const PublicController = {
    // 用户注册
    createUser: {
        gateway,
        service,
        controller,
        path: '/api/public/register',
        action: 'createUser',
        type: RequestMethod.Post
    }
}
