/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { PayedController } from '@/http/controller/learn-service/payed.controller'

export class PayedService {
  /**
   * 外部订单支付成功
   */
  @Request({
    server: PayedController.paySuccessRequest,
  })
  public paySuccessRequest(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
