/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { PrePayController } from '@/http/controller/learn-service/pre-pay.controller'

export class PrePayService {
  /**
   * 微信支付生成微信预支付订单(assistant调用)
   */
  @Request({
    server: PrePayController.prePayRequest,
  })
  public prePayRequest(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
