/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { QuestionController } from '@/http/controller/learn-service/question.controller'

export class QuestionService {
  /**
   * 取消点赞
   */
  @Request({
    server: QuestionController.unstar,
  })
  public unstar(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 问题点赞
   */
  @Request({
    server: QuestionController.star,
  })
  public star(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 标记问题已完成
   */
  @Request({
    server: QuestionController.done,
  })
  public done(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
