/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { SyslogController } from '@/http/controller/learn-service/syslog.controller'
import { SystemLog } from '@/http/model/learn-service.model'

export class SyslogService {
  /**
   * 操作日志（分页查询)
   */
  @Request({
    server: SyslogController.pageableSysLog,
    model: SystemLog
  })
  public pageableSysLog(
    params?: RequestParams | { [key: string]: any }
  ): Observable<SystemLog[]> {
    return RequestParams.create(params).request();
  }
}
