/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { CosController } from '@/http/controller/assistant-service/cos.controller'
import { COSUploadUrlResponse, COSTempSecretResponse } from '@/http/model/assistant-service.model'

export class CosService {
  /**
   * 创建临时上传链接
   */
  @Request({
    server: CosController.createUploadUrl,
    model: COSUploadUrlResponse
  })
  public createUploadUrl(
    params?: RequestParams | { [key: string]: any }
  ): Observable<COSUploadUrlResponse> {
    return RequestParams.create(params).request();
  }
  /**
   * 创建临时Secret
   */
  @Request({
    server: CosController.createTempSecret,
    model: COSTempSecretResponse
  })
  public createTempSecret(
    params?: RequestParams | { [key: string]: any }
  ): Observable<COSTempSecretResponse> {
    return RequestParams.create(params).request();
  }
  /**
   * 腾讯COS预授权URL
   */
  @Request({
    server: CosController.generatePresignedUrl,
  })
  public generatePresignedUrl(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
