/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { MicroappController } from '@/http/controller/assistant-service/microapp.controller'

export class MicroappService {
  /**
   * 用户信息
   */
  @Request({
    server: MicroappController.userInfo,
  })
  public userInfo(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 电话号码
   */
  @Request({
    server: MicroappController.userPhone,
  })
  public userPhone(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 小程序获取unionId及sessionKey
   */
  @Request({
    server: MicroappController.fetchUserIds,
  })
  public fetchUserIds(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
