/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'login'
const service = 'as'
const gateway = 'default'

export const LoginController = {
    // 用户名，密码登录
    loginWithUserName: {
        gateway,
        service,
        controller,
        path: '/login',
        action: 'loginWithUserName',
        type: RequestMethod.Post
    },
    // 微信登录
    loginWithWxMpCode: {
        gateway,
        service,
        controller,
        path: '/login/mp',
        action: 'loginWithWxMpCode',
        type: RequestMethod.Post
    }
}
